# Generated by Django 2.2.1 on 2019-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='import_description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
